
var cellCountryCodes = [
    { code: '1', name: 'United States', country: 'USA', lang: 'eng' },
    { code: '86', name: 'China', country: 'CHN', lang: 'zho' },
    { code: '44', name: 'United Kingdom', country: 'GBR', lang: 'eng' },
    { code: '1', name: 'Canada', country: 'CAN', lang: 'eng' },
    { code: '1-242', name: 'Bahamas', country: 'BHS', lang: 'eng' },
    { code: '1-246', name: 'Barbados', country: 'BRB', lang: 'spa' },
    { code: '1-264', name: 'Anguilla', country: 'AIA', lang: 'eng' },
    { code: '1-268', name: 'Antigua and Barbuda', country: 'ATG', lang: 'eng' },
    { code: '1-284', name: 'British Virgin Islands', country: 'VGB', lang: 'eng' },
    { code: '1-340', name: 'U.S. Virgin Islands', country: 'VIR', lang: 'eng' },
    { code: '1-345', name: 'Cayman Islands', country: 'CYM', lang: 'eng' },
    { code: '1-441', name: 'Bermuda', country: 'BMU', lang: 'eng' },
    { code: '1-473', name: 'Grenada', country: 'GRD', lang: 'eng' },
    { code: '1-649', name: 'Turks and Caicos Islands', country: 'TCA', lang: 'eng' },
    { code: '1-664', name: 'Montserrat', country: 'MSR', lang: 'eng' },
    { code: '1-670', name: 'Northern Mariana Islands', country: 'MNP', lang: 'eng' },
    { code: '1-671', name: 'Guam', country: 'GUM', lang: 'eng' },
    { code: '1-684', name: 'American Samoa', country: 'ASM', lang: 'eng' },
    { code: '1-721', name: 'Sint Maarten', country: 'SXM', lang: 'nld' },
    { code: '1-758', name: 'Saint Lucia', country: 'LCA', lang: 'eng' },
    { code: '1-767', name: 'Dominica', country: 'DMA', lang: 'eng' },
    { code: '1-784', name: 'Saint Vincent and the Grenadines', country: 'VCT', lang: 'eng' },
    { code: '1-787', name: 'Puerto Rico', country: 'PRI', lang: 'spa' },
    { code: '1-939', name: 'Puerto Rico', country: 'PRI', lang: 'spa' },
    { code: '1-809', name: 'Dominican Republic', country: 'DOM', lang: 'spa' },
    { code: '1-829', name: 'Dominican Republic', country: 'DOM', lang: 'spa' },
    { code: '1-849', name: 'Dominican Republic', country: 'DOM', lang: 'spa' },
    { code: '1-868', name: 'Trinidad and Tobago', country: 'TTO', lang: 'eng' },
    { code: '1-869', name: 'Saint Kitts and Nevis', country: 'KNA', lang: 'eng' },
    { code: '1-876', name: 'Jamaica', country: 'JAM', lang: 'spa' },
    { code: '20', name: 'Egypt', country: 'EGY', lang: 'ara' },
    { code: '211', name: 'South Sudan', country: 'SSD', lang: 'eng' },
    { code: '212', name: 'Morocco', country: 'MAR', lang: 'ara' },
    { code: '212', name: 'Western Sahara', country: 'ESH', lang: 'ara' },
    { code: '213', name: 'Algeria', country: 'DZA', lang: 'ara' },
    { code: '216', name: 'Tunisia', country: 'TUN', lang: 'ara' },
    { code: '218', name: 'Libya', country: 'LBY', lang: 'ara' },
    { code: '220', name: 'Gambia', country: 'GMB', lang: 'eng' },
    { code: '221', name: 'Senegal', country: 'SEN', lang: 'fra' },
    { code: '222', name: 'Mauritania', country: 'MRT', lang: 'ara' },
    { code: '223', name: 'Mali', country: 'MLI', lang: 'fra' },
    { code: '224', name: 'Guinea', country: 'GIN', lang: 'fra' },
    { code: '225', name: 'Ivory Coast', country: 'CIV', lang: 'fra' },
    { code: '226', name: 'Burkina Faso', country: 'BFA', lang: 'fra' },
    { code: '227', name: 'Niger', country: 'NER', lang: 'fra' },
    { code: '228', name: 'Togo', country: 'TGO', lang: 'fra' },
    { code: '229', name: 'Benin', country: 'BEN', lang: 'fra' },
    { code: '230', name: 'Mauritius', country: 'MUS', lang: 'eng' },
    { code: '231', name: 'Liberia', country: 'LBR', lang: 'eng' },
    { code: '232', name: 'Sierra Leone', country: 'SLE', lang: 'eng' },
    { code: '233', name: 'Ghana', country: 'GHA', lang: 'eng' },
    { code: '234', name: 'Nigeria', country: 'NGA', lang: 'eng' },
    { code: '235', name: 'Chad', country: 'TCD', lang: 'fra' },
    { code: '236', name: 'Central African Republic', country: 'CAF', lang: 'fra' },
    { code: '237', name: 'Cameroon', country: 'CMR', lang: 'fra' },
    { code: '238', name: 'Cape Verde', country: 'CPV', lang: 'por' },
    { code: '239', name: 'Sao Tome and Principe', country: 'STP', lang: 'por' },
    { code: '240', name: 'Equatorial Guinea', country: 'GNQ', lang: 'por' },
    { code: '241', name: 'Gabon', country: 'GAB', lang: 'fra' },
    { code: '242', name: 'Republic of the Congo', country: 'COG', lang: 'fra' },
    { code: '243', name: 'Democratic Republic of the Congo', country: 'COD', lang: 'fra' },
    { code: '244', name: 'Angola', country: 'AGO', lang: 'por' },
    { code: '245', name: 'Guinea-Bissau', country: 'GNB', lang: 'por' },
    { code: '246', name: 'British Indian Ocean Territory', country: 'IOT', lang: 'eng' },
    { code: '248', name: 'Seychelles', country: 'SYC', lang: 'fra' },
    { code: '249', name: 'Sudan', country: 'SDN', lang: 'ara' },
    { code: '250', name: 'Rwanda', country: 'RWA', lang: 'kin' },
    { code: '251', name: 'Ethiopia', country: 'ETH', lang: 'amh' },
    { code: '252', name: 'Somalia', country: 'SOM', lang: 'som' },
    { code: '253', name: 'Djibouti', country: 'DJI', lang: 'fra' },
    { code: '254', name: 'Kenya', country: 'KEN', lang: 'swa' },
    { code: '255', name: 'Tanzania', country: 'TZA', lang: 'swa' },
    { code: '256', name: 'Uganda', country: 'UGA', lang: 'eng' },
    { code: '257', name: 'Burundi', country: 'BDI', lang: 'fra' },
    { code: '258', name: 'Mozambique', country: 'MOZ', lang: 'por' },
    { code: '260', name: 'Zambia', country: 'ZMB', lang: 'eng' },
    { code: '263', name: 'Zimbabwe', country: 'ZWE', lang: 'eng' },
    { code: '261', name: 'Madagascar', country: 'MDG', lang: 'fra' },
    { code: '262', name: 'Mayotte', country: 'MYT', lang: 'fra' },
    { code: '262', name: 'Reunion', country: 'REU', lang: 'fra' },
    { code: '264', name: 'Namibia', country: 'NAM', lang: 'eng' },
    { code: '265', name: 'Malawi', country: 'MWI', lang: 'eng' },
    { code: '266', name: 'Lesotho', country: 'LSO', lang: 'eng' },
    { code: '267', name: 'Botswana', country: 'BWA', lang: 'eng' },
    { code: '268', name: 'Swaziland', country: 'SWZ', lang: 'eng' },
    { code: '269', name: 'Comoros', country: 'COM', lang: 'swa' },
    { code: '27', name: 'South Africa', country: 'ZAF', lang: 'eng' },
    { code: '290', name: 'Saint Helena', country: 'SHN', lang: 'eng' },
    { code: '291', name: 'Eritrea', country: 'ERI', lang: 'tir' },
    { code: '297', name: 'Aruba', country: 'ABW', lang: 'nld' },
    { code: '298', name: 'Faroe Islands', country: 'FRO', lang: 'fao' },
    { code: '299', name: 'Greenland', country: 'GRL', lang: 'kal' },
    { code: '30', name: 'Greece', country: 'GRC', lang: 'ell' },
    { code: '31', name: 'Netherlands', country: 'NLD', lang: 'deu' },
    { code: '32', name: 'Belgium', country: 'BEL', lang: 'nld' },
    { code: '33', name: 'France', country: 'FRA', lang: 'fra' },
    { code: '34', name: 'Spain', country: 'ESP', lang: 'spa' },
    { code: '350', name: 'Gibraltar', country: 'GIB', lang: 'eng' },
    { code: '351', name: 'Portugal', country: 'PRT', lang: 'por' },
    { code: '352', name: 'Luxembourg', country: 'LUX', lang: 'ltz' },
    { code: '353', name: 'Ireland', country: 'IRL', lang: 'gle' },
    { code: '354', name: 'Iceland', country: 'ISL', lang: 'isl' },
    { code: '355', name: 'Albania', country: 'ALB', lang: 'sqi' },
    { code: '356', name: 'Malta', country: 'MLT', lang: 'mlt' },
    { code: '357', name: 'Cyprus', country: 'CYP', lang: 'ell' },
    { code: '358', name: 'Finland', country: 'FIN', lang: 'fin' },
    { code: '359', name: 'Bulgaria', country: 'BGR', lang: 'bul' },
    { code: '36', name: 'Hungary', country: 'HUN', lang: 'hun' },
    { code: '370', name: 'Lithuania', country: 'LTU', lang: 'lit' },
    { code: '371', name: 'Latvia', country: 'LVA', lang: 'lav' },
    { code: '372', name: 'Estonia', country: 'EST', lang: 'est' },
    { code: '373', name: 'Moldova', country: 'MDA', lang: 'ron' },
    { code: '374', name: 'Armenia', country: 'ARM', lang: 'hye' },
    { code: '375', name: 'Belarus', country: 'BLR', lang: 'bel' },
    { code: '376', name: 'Andorra', country: 'AND', lang: 'cat' },
    { code: '377', name: 'Monaco', country: 'MCO', lang: 'fra' },
    { code: '378', name: 'San Marino', country: 'SMR', lang: 'ita' },
    { code: '379', name: 'Vatican', country: 'VAT', lang: 'ita' },
    { code: '380', name: 'Ukraine', country: 'UKR', lang: 'ukr' },
    { code: '381', name: 'Serbia', country: 'SRB', lang: 'srp' },
    { code: '382', name: 'Montenegro', country: 'MNE', lang: 'srp' },
    { code: '383', name: 'Kosovo', country: 'XKX', lang: 'sqi' },
    { code: '385', name: 'Croatia', country: 'HRV', lang: 'hrv' },
    { code: '386', name: 'Slovenia', country: 'SVN', lang: 'slv' },
    { code: '387', name: 'Bosnia and Herzegovina', country: 'BIH', lang: 'bos' },
    { code: '389', name: 'Macedonia', country: 'MKD', lang: 'mkd' },
    { code: '39', name: 'Italy', country: 'ITA', lang: 'ita' },
    { code: '40', name: 'Romania', country: 'ROU', lang: 'ron' },
    { code: '41', name: 'Switzerland', country: 'CHE', lang: 'deu' },
    { code: '420', name: 'Czech Republic', country: 'CZE', lang: 'ces' },
    { code: '421', name: 'Slovakia', country: 'SVK', lang: 'slk' },
    { code: '423', name: 'Liechtenstein', country: 'LIE', lang: 'deu' },
    { code: '43', name: 'Austria', country: 'AUT', lang: 'deu' },
    { code: '44-1481', name: 'Guernsey', country: 'GGY', lang: 'eng' },
    { code: '44-1534', name: 'Jersey', country: 'JEY', lang: 'eng' },
    { code: '44-1624', name: 'Isle of Man', country: 'IMN', lang: 'eng' },
    { code: '45', name: 'Denmark', country: 'DNK', lang: 'dan' },
    { code: '46', name: 'Sweden', country: 'SWE', lang: 'swe' },
    { code: '47', name: 'Norway', country: 'NOR', lang: 'nor' },
    { code: '47', name: 'Svalbard and Jan Mayen', country: 'SJM', lang: 'nor' },
    { code: '48', name: 'Poland', country: 'POL', lang: 'pol' },
    { code: '49', name: 'Germany', country: 'DEU', lang: 'deu' },
    { code: '500', name: 'Falkland Islands', country: 'FLK', lang: 'eng' },
    { code: '501', name: 'Belize', country: 'BLZ', lang: 'eng' },
    { code: '502', name: 'Guatemala', country: 'GTM', lang: 'spa' },
    { code: '503', name: 'El Salvador', country: 'SLV', lang: 'spa' },
    { code: '504', name: 'Honduras', country: 'HND', lang: 'spa' },
    { code: '505', name: 'Nicaragua', country: 'NIC', lang: 'spa' },
    { code: '506', name: 'Costa Rica', country: 'CRI', lang: 'spa' },
    { code: '507', name: 'Panama', country: 'PAN', lang: 'spa' },
    { code: '508', name: 'Saint Pierre and Miquelon', country: 'SPM', lang: 'fra' },
    { code: '509', name: 'Haiti', country: 'HTI', lang: 'fra' },
    { code: '51', name: 'Peru', country: 'PER', lang: 'spa' },
    { code: '52', name: 'Mexico', country: 'MEX', lang: 'spa' },
    { code: '53', name: 'Cuba', country: 'CUB', lang: 'spa' },
    { code: '54', name: 'Argentina', country: 'ARG', lang: 'spa' },
    { code: '55', name: 'Brazil', country: 'BRA', lang: 'por' },
    { code: '56', name: 'Chile', country: 'CHL', lang: 'spa' },
    { code: '57', name: 'Colombia', country: 'COL', lang: 'spa' },
    { code: '58', name: 'Venezuela', country: 'VEN', lang: 'spa' },
    { code: '590', name: 'Saint Barthelemy', country: 'BLM', lang: 'fra' },
    { code: '590', name: 'Saint Martin', country: 'MAF', lang: 'fra' },
    { code: '591', name: 'Bolivia', country: 'BOL', lang: 'spa' },
    { code: '592', name: 'Guyana', country: 'GUY', lang: 'eng' },
    { code: '593', name: 'Ecuador', country: 'ECU', lang: 'spa' },
    { code: '595', name: 'Paraguay', country: 'PRY', lang: 'spa' },
    { code: "596", name: "Martinique", country: "MTQ", lang: "fra" },
    { code: '597', name: 'Suriname', country: 'SUR', lang: 'nld' },
    { code: '598', name: 'Uruguay', country: 'URY', lang: 'spa' },
    { code: '599', name: 'Curacao', country: 'CUW', lang: 'spa' },
    { code: '599', name: 'Netherlands Antilles', country: 'ANT', lang: 'nld' },
    { code: '60', name: 'Malaysia', country: 'MYS', lang: 'msa' },
    { code: '61', name: 'Australia', country: 'AUS', lang: 'eng' },
    { code: '61', name: 'Christmas Island', country: 'CXR', lang: 'eng' },
    { code: '61', name: 'Cocos Islands', country: 'CCK', lang: 'eng' },
    { code: '62', name: 'Indonesia', country: 'IDN', lang: 'ind' },
    { code: '63', name: 'Philippines', country: 'PHL', lang: 'fil' },
    { code: '64', name: 'New Zealand', country: 'NZL', lang: 'eng' },
    { code: '64', name: 'Pitcairn', country: 'PCN', lang: 'eng' },
    { code: '65', name: 'Singapore', country: 'SGP', lang: 'eng' },
    { code: '66', name: 'Thailand', country: 'THA', lang: 'tha' },
    { code: '670', name: 'East Timor', country: 'TLS', lang: 'tdt' },
    { code: '672', name: 'Antarctica', country: 'ATA', lang: 'eng' },
    { code: '673', name: 'Brunei', country: 'BRN', lang: 'msa' },
    { code: '674', name: 'Nauru', country: 'NRU', lang: 'eng' },
    { code: '675', name: 'Papua New Guinea', country: 'PNG', lang: 'eng' },
    { code: '676', name: 'Tonga', country: 'TON' },
    { code: '677', name: 'Solomon Islands', country: 'SLB', lang: 'eng' },
    { code: '678', name: 'Vanuatu', country: 'VUT', lang: 'eng' },
    { code: '679', name: 'Fiji', country: 'FJI', lang: 'eng' },
    { code: '680', name: 'Palau', country: 'PLW', lang: 'eng' },
    { code: '681', name: 'Wallis and Futuna', country: 'WLF', lang: 'fra' },
    { code: '682', name: 'Cook Islands', country: 'COK', lang: 'eng' },
    { code: '683', name: 'Niue', country: 'NIU', lang: 'niu' },
    { code: '685', name: 'Samoa', country: 'WSM', lang: 'smo' },
    { code: '686', name: 'Kiribati', country: 'KIR', lang: 'eng' },
    { code: '687', name: 'New Caledonia', country: 'NCL', lang: 'fra' },
    { code: '688', name: 'Tuvalu', country: 'TUV', lang: 'tvl' },
    { code: '689', name: 'French Polynesia', country: 'PYF', lang: 'fra' },
    { code: '690', name: 'Tokelau', country: 'TKL', lang: 'tkl' },
    { code: '691', name: 'Micronesia', country: 'FSM', lang: 'eng' },
    { code: '692', name: 'Marshall Islands', country: 'MHL', lang: 'mah' },
    { code: '7', name: 'Kazakhstan', country: 'KAZ', lang: 'kaz' },
    { code: '7', name: 'Russia', country: 'RUS', lang: 'rus' },
    { code: '81', name: 'Japan', country: 'JPN', lang: 'jpn' },
    { code: '82', name: 'South Korea', country: 'KOR', lang: 'kor' },
    { code: '84', name: 'Vietnam', country: 'VNM', lang: 'vie' },
    { code: '850', name: 'North Korea', country: 'PRK', lang: 'kor' },
    { code: '852', name: 'Hong Kong', country: 'HKG' },
    { code: '853', name: 'Macau', country: 'MAC' },
    { code: '855', name: 'Cambodia', country: 'KHM' },
    { code: '856', name: 'Laos', country: 'LAO', lang: 'lao' },
    { code: '880', name: 'Bangladesh', country: 'BGD', lang: 'eng' },
    { code: '886', name: 'Taiwan', country: 'TWN' },
    { code: '90', name: 'Turkey', country: 'TUR', lang: 'tur' },
    { code: '91', name: 'India', country: 'IND', lang: 'hin' },
    { code: '92', name: 'Pakistan', country: 'PAK', lang: 'urd' },
    { code: '93', name: 'Afghanistan', country: 'AFG', lang: 'pus' },
    { code: '94', name: 'Sri Lanka', country: 'LKA', lang: 'sin' },
    { code: '95', name: 'Myanmar', country: 'MMR', lang: 'mya' },
    { code: '960', name: 'Maldives', country: 'MDV', lang: 'div' },
    { code: '961', name: 'Lebanon', country: 'LBN', lang: 'ara' },
    { code: '962', name: 'Jordan', country: 'JOR', lang: 'ara' },
    { code: '963', name: 'Syria', country: 'SYR', lang: 'ara' },
    { code: '964', name: 'Iraq', country: 'IRQ', lang: 'ara' },
    { code: '965', name: 'Kuwait', country: 'KWT', lang: 'ara' },
    { code: '966', name: 'Saudi Arabia', country: 'SAU', lang: 'ara' },
    { code: '967', name: 'Yemen', country: 'YEM', lang: 'ara' },
    { code: '968', name: 'Oman', country: 'OMN', lang: 'ara' },
    { code: '970', name: 'Palestine', country: 'PSE', lang: 'ara' },
    { code: '971', name: 'United Arab Emirates', country: 'ARE', lang: 'ara' },
    { code: '972', name: 'Israel', country: 'ISR', lang: 'heb' },
    { code: '973', name: 'Bahrain', country: 'BHR', lang: 'ara' },
    { code: '974', name: 'Qatar', country: 'QAT', lang: 'ara' },
    { code: '975', name: 'Bhutan', country: 'BTN', lang: 'dzo' },
    { code: '976', name: 'Mongolia', country: 'MNG', lang: 'mon' },
    { code: '977', name: 'Nepal', country: 'NPL', lang: 'nep' },
    { code: '98', name: 'Iran', country: 'IRN', lang: 'fas' },
    { code: '992', name: 'Tajikistan', country: 'TJK', lang: 'tgk' },
    { code: '993', name: 'Turkmenistan', country: 'TKM', lang: 'tuk' },
    { code: '994', name: 'Azerbaijan', country: 'AZE', lang: 'aze' },
    { code: '995', name: 'Georgia', country: 'GEO', lang: 'eng' },
    { code: '996', name: 'Kyrgyzstan', country: 'KGZ', lang: 'kir' },
    { code: '998', name: 'Uzbekistan', country: 'UZB', lang: 'uzb' }
];
var currencyCountries = [
    { country: 'AFG', currency: 'AFN' },
    { country: 'ÅLA', currency: 'EUR' },
    { country: 'ALB', currency: 'ALL' },
    { country: 'DZA', currency: 'DZD' },
    { country: 'ASM', currency: 'USD' },
    { country: 'AND', currency: 'EUR' },
    { country: 'AGO', currency: 'AOA' },
    { country: 'AIA', currency: 'XCD' },
    { country: 'ATG', currency: 'XCD' },
    { country: 'ARG', currency: 'ARS' },
    { country: 'ARM', currency: 'AMD' },
    { country: 'ABW', currency: 'AWG' },
    { country: 'AUS', currency: 'AUD' },
    { country: 'AUT', currency: 'EUR' },
    { country: 'AZE', currency: 'AZN' },
    { country: 'BHS', currency: 'BSD' },
    { country: 'RHR', currency: 'BHD' },
    { country: 'BGD', currency: 'BDT' },
    { country: 'BRB', currency: 'BBD' },
    { country: 'BLR', currency: 'BYN' },
    { country: 'BEL', currency: 'EUR' },
    { country: 'BLZ', currency: 'BZD' },
    { country: 'BEN', currency: 'XOF' },
    { country: 'BMU', currency: 'BMD' },
    { country: 'BTN', currency: 'INR' },
    { country: 'BOL', currency: 'BOV' },
    { country: 'BES', currency: 'USD' },
    { country: 'BIH', currency: 'BAM' },
    { country: 'BWA', currency: 'BWP' },
    { country: 'BVT', currency: 'NOK' },
    { country: 'BRA', currency: 'BRL' },
    { country: 'IOT', currency: 'USD' },
    { country: 'BRN', currency: 'BND' },
    { country: 'BGR', currency: 'BGN' },
    { country: 'BFA', currency: 'XOF' },
    { country: 'CPV', currency: 'CVE' },
    { country: 'KHM', currency: 'KHR' },
    { country: 'CMR', currency: 'XAF' },
    { country: 'CAN', currency: 'CAD' },
    { country: 'CYM', currency: 'KYD' },
    { country: 'CAF', currency: 'XAF' },
    { country: 'TCD', currency: 'XAF' },
    { country: 'CHL', currency: 'CLP' },
    { country: 'CHN', currency: 'CNY' },
    { country: 'CXR', currency: 'AUD' },
    { country: 'CCK', currency: 'AUD' },
    { country: 'COL', currency: 'COP' },
    { country: 'COM', currency: 'KMF' },
    { country: 'COG', currency: 'CDF' },
    { country: 'COK', currency: 'NZD' },
    { country: 'CRI', currency: 'CRC' },
    { country: 'CIV', currency: 'XOF' },
    { country: 'HRV', currency: 'HRK' },
    { country: 'CUB', currency: 'CUC' },
    { country: 'CUW', currency: 'ANG' },
    { country: 'CYP', currency: 'EUR' },
    { country: 'CZE', currency: 'CZK' },
    { country: 'DNK', currency: 'DKK' },
    { country: 'DJI', currency: 'DJF' },
    { country: 'DOM', currency: 'DOP' },
    { country: 'DMA', currency: 'XCD' },
    { country: 'ECU', currency: 'USD' },
    { country: 'EGY', currency: 'EGP' },
    { country: 'SLV', currency: 'SVC' },
    { country: 'GNQ', currency: 'XAF' },
    { country: 'ERI', currency: 'ERN' },
    { country: 'EST', currency: 'EUR' },
    { country: 'ETH', currency: 'ETB' },
    { country: 'FLK', currency: 'FKP' },
    { country: 'FRO', currency: 'DKK' },
    { country: 'FJI', currency: 'FJD' },
    { country: 'FIN', currency: 'EUR' },
    { country: 'FRA', currency: 'EUR' },
    { country: 'GUF', currency: 'EUR' },
    { country: 'PYF', currency: 'XPF' },
    { country: 'ATF', currency: 'EUR' },
    { country: 'GAB', currency: 'XAF' },
    { country: 'GMB', currency: 'GMD' },
    { country: 'GEO', currency: 'GEL' },
    { country: 'DEU', currency: 'EUR' },
    { country: 'GHA', currency: 'GHS' },
    { country: 'GIB', currency: 'GIP' },
    { country: 'GRC', currency: 'EUR' },
    { country: 'GRL', currency: 'DKK' },
    { country: 'GRD', currency: 'XCD' },
    { country: 'GLP', currency: 'EUR' },
    { country: 'GUM', currency: 'USD' },
    { country: 'GTM', currency: 'GTQ' },
    { country: 'GGY', currency: 'GBP' },
    { country: 'GNB', currency: 'XOF' },
    { country: 'GUY', currency: 'GYD' },
    { country: 'HTI', currency: 'USD' },
    { country: 'HMD', currency: 'AUD' },
    { country: 'VAT', currency: 'EUR' },
    { country: 'HND', currency: 'HNL' },
    { country: 'HKG', currency: 'HKD' },
    { country: 'HUN', currency: 'HUF' },
    { country: 'ISL', currency: 'ISK' },
    { country: 'IND', currency: 'INR' },
    { country: 'IDN', currency: 'IDR' },
    { country: 'IRN', currency: 'IRR' },
    { country: 'IRQ', currency: 'IQD' },
    { country: 'IRL', currency: 'EUR' },
    { country: 'IMN', currency: 'GBP' },
    { country: 'ISR', currency: 'ILS' },
    { country: 'ITA', currency: 'EUR' },
    { country: 'JAM', currency: 'JMD' },
    { country: 'JPN', currency: 'JPY' },
    { country: 'JEY', currency: 'GBP' },
    { country: 'JOR', currency: 'JOD' },
    { country: 'KAZ', currency: 'KZT' },
    { country: 'KEN', currency: 'KES' },
    { country: 'KIR', currency: 'AUD' },
    { country: 'PRK', currency: 'KPW' },
    { country: 'KOR', currency: 'KRW' },
    { country: 'KWT', currency: 'KWD' },
    { country: 'KGZ', currency: 'KGS' },
    { country: 'LAO', currency: 'LAK' },
    { country: 'LVA', currency: 'EUR' },
    { country: 'LBN', currency: 'LBP' },
    { country: 'LSO', currency: 'LSL' },
    { country: 'LBR', currency: 'LRD' },
    { country: 'LBY', currency: 'LYD' },
    { country: 'LIE', currency: 'CHF' },
    { country: 'LTU', currency: 'EUR' },
    { country: 'LUX', currency: 'EUR' },
    { country: 'MAC', currency: 'MOP' },
    { country: 'MDG', currency: 'MGA' },
    { country: 'MWI', currency: 'MWK' },
    { country: 'MYS', currency: 'MYR' },
    { country: 'MDV', currency: 'MVR' },
    { country: 'MLI', currency: 'XOF' },
    { country: 'MLT', currency: 'EUR' },
    { country: 'MHL', currency: 'USD' },
    { country: 'MTQ', currency: 'EUR' },
    { country: 'MRT', currency: 'MRU' },
    { country: 'MUS', currency: 'MUR' },
    { country: 'MYT', currency: 'EUR' },
    { country: 'MEX', currency: 'MXN' },
    { country: 'FSM', currency: 'USD' },
    { country: 'MDA', currency: 'MDL' },
    { country: 'MCO', currency: 'EUR' },
    { country: 'MNG', currency: 'MNT' },
    { country: 'MNE', currency: 'EUR' },
    { country: 'MSR', currency: 'XCD' },
    { country: 'MAR', currency: 'MAD' },
    { country: 'MKD', currency: 'USD' },
    { country: 'MOZ', currency: 'MZN' },
    { country: 'MMR', currency: 'MMK' },
    { country: 'NAM', currency: 'NAD' },
    { country: 'NRU', currency: 'AUD' },
    { country: 'NPL', currency: 'NPR' },
    { country: 'NLD', currency: 'EUR' },
    { country: 'NCL', currency: 'XPF' },
    { country: 'NZL', currency: 'NZD' },
    { country: 'NIC', currency: 'NIO' },
    { country: 'NER', currency: 'XOF' },
    { country: 'NGA', currency: 'NGN' },
    { country: 'NIU', currency: 'NZD' },
    { country: 'NFK', currency: 'AUD' },
    { country: 'MNP', currency: 'USD' },
    { country: 'NOR', currency: 'NOK' },
    { country: 'OMN', currency: 'OMR' },
    { country: 'PAK', currency: 'PKR' },
    { country: 'PLW', currency: 'USD' },
    { country: 'PAN', currency: 'USD' },
    { country: 'PNG', currency: 'PGK' },
    { country: 'PRY', currency: 'PYG' },
    { country: 'PER', currency: 'PEN' },
    { country: 'PHL', currency: 'PHP' },
    { country: 'PCN', currency: 'NZD' },
    { country: 'POL', currency: 'PLN' },
    { country: 'PRT', currency: 'EUR' },
    { country: 'PRI', currency: 'USD' },
    { country: 'QAT', currency: 'QAR' },
    { country: 'REU', currency: 'EUR' },
    { country: 'ROU', currency: 'RON' },
    { country: 'RUS', currency: 'RUB' },
    { country: 'RWA', currency: 'RWF' },
    { country: 'BLM', currency: 'EUR' },
    { country: 'SHN', currency: 'SHP' },
    { country: 'KNA', currency: 'XCD' },
    { country: 'LCA', currency: 'XCD' },
    { country: 'MAF', currency: 'EUR' },
    { country: 'SPM', currency: 'EUR' },
    { country: 'VCT', currency: 'XCD' },
    { country: 'WSM', currency: 'WST' },
    { country: 'SMR', currency: 'EUR' },
    { country: 'STP', currency: 'STN' },
    { country: 'SAU', currency: 'SAR' },
    { country: 'SEN', currency: 'XOF' },
    { country: 'SRB', currency: 'RSD' },
    { country: 'SYC', currency: 'SCR' },
    { country: 'SLE', currency: 'SLL' },
    { country: 'SGP', currency: 'SGD' },
    { country: 'SXM', currency: 'ANG' },
    { country: 'SVK', currency: 'EUR' },
    { country: 'SVN', currency: 'EUR' },
    { country: 'SLB', currency: 'SBD' },
    { country: 'ZAF', currency: 'ZAR' },
    { country: 'SSD', currency: 'SSP' },
    { country: 'ESP', currency: 'EUR' },
    { country: 'LKA', currency: 'LKR' },
    { country: 'SDN', currency: 'SDG' },
    { country: 'SUR', currency: 'SRD' },
    { country: 'SJM', currency: 'NOK' },
    { country: 'CHE', currency: 'SZL' },
    { country: 'SWE', currency: 'SEK' },
    { country: 'SYR', currency: 'SYP' },
    { country: 'TWN', currency: 'TWD' },
    { country: 'TJK', currency: 'TJS' },
    { country: 'TZA', currency: 'TZS' },
    { country: 'THA', currency: 'THB' },
    { country: 'TLS', currency: 'USD' },
    { country: 'TGO', currency: 'XOF' },
    { country: 'TKL', currency: 'NZD' },
    { country: 'TON', currency: 'TOP' },
    { country: 'TTO', currency: 'TTD' },
    { country: 'TUN', currency: 'TND' },
    { country: 'TUR', currency: 'TRY' },
    { country: 'TKM', currency: 'TMT' },
    { country: 'TCA', currency: 'USD' },
    { country: 'TUV', currency: 'AUD' },
    { country: 'UGA', currency: 'UGX' },
    { country: 'UKR', currency: 'UAH' },
    { country: 'ARE', currency: 'AED' },
    { country: 'GBR', currency: 'GBP' },
    { country: 'UMI', currency: 'USD' },
    { country: 'USA', currency: 'USD' },
    { country: 'URY', currency: 'UYI' },
    { country: 'UZB', currency: 'UZS' },
    { country: 'VUT', currency: 'VUV' },
    { country: 'VEN', currency: 'VEF' },
    { country: 'VNM', currency: 'VND' },
    { country: 'VGB', currency: 'USD' },
    { country: 'VIR', currency: 'USD' },
    { country: 'WLF', currency: 'XPF' },
    { country: 'ESH', currency: 'MAD' },
    { country: 'XXK', currency: 'USD' },
    { country: 'YEM', currency: 'YER' },
    { country: 'ZMB', currency: 'ZMW' },
    { country: 'ZWE', currency: 'ZWL' }
]


