var spaTrans = {
    "after-sign-in": {
        "add-new-rule-text": "Add New rule",
        "meet-greet-price-box--lbl-": "Meet Greet Charge",
        "unit-price-box--lbl-": "Unit Price *",
        "unit-price-box-hourly--lbl-": "Unit Price *",
        "item-currency-0": "Price",
        "item-amounts-0": "Fleet Range",
        "to-place": "Please enter your to place",
        "from-place": "Please enter your from place",
        "country": "Please select a country *",
        "svc-aea-search-tab-title": "Service Area",
        "code-name": "Please enter airport code *",
        "service-area-search-fld": "Please enter service area or airport partial words",
        "add-service-area-text": "Add Service Area",
        "svc-aea-btn": "Service Area",
        "vehicle-manage": "Vehicle Management",
        "partner-setting-btn": "Partner",
        "servicing-airports-title": "Service Area",
        "basic-pricing-title": "Range Prices",
        "hourly-pricing-title": "Hourly Prices Setting",
        "add-zones-title": "Fixed Price Zones",
        "vehicles-pricing-title": "Vehicles Pricing",
        "reserve-time-title": "Reserve Time",
        "personalised-time-title": "Service Time",
        "save-page-title": "Save",
        "prev-btn": "Prev",
        "next-btn": "Next",
        "servicing-airports-save-btn": "Save",
        // "price-rule-setting-btn": "Set Price Rules",
        "service-area-name-title": "Servicing Area",
        "service-airports-title": "Serving Airports",
        "service-radius-title": "Setting Radius",
        "btn-add-airport": "Add Service Airport",
        "basic-price-text": "Distance based Pricing",
        "meet-sign-title": "Meet And Greet",
        "add-duration": "Add duration and Price",
        "add-dis-pirce": "Add Distance and Price",
        "calc-btn": "Calc",
        "calc-btn-hourly": "Calc",
        "calculator-title": "Calculating by the unit prices you had set",
        "distance-import-fld": "Please enter the distance value",
        "calculator-title-hourly": "Calculating by the unit prices you had set",
        "hourly-price-title": "Hourly Pricing",
        "zone-pricing-explain": "Special zone pricing:create fixed price for special zones",
        "zone-add-text": "Add Zone",
        "zone-reloc-fld": "Enter keywords to search area",
        "airport-names-lbl": "From Airports",
        "airport-prices-lbl": "Fixed Price",
        "airport-distances-lbl": "Distance",
        "small-vehicles-title": "Small car",
        "luxury-vehicles-title": "Luxury car",
        "large-vehicles-title": "Large car",
        "currency-title": "Currency:",
        "add-personalised-time": "Add personalised time:",
        "add-new-rule": "Add New rule",
        "Normal-reserve-text": "Normal reserve *",
        "in-advance": "In advance",
        "extra-charge": "Extra charge",
        "save-title": "Confirm Save",
        "btn-download": "Download Price CSV Sheet",
        "code-input": "Verification code",
        "save-textarea": "Please enter note",
        "btn-save": "Save",
        "save-tip": "The price will take effect immediately after saving, please enter the verification code to confirm saving",
        "partner-price-setting-title-bar": "Partner",
        "add-partner": "Add partner",
        "partner-name-lbl": "Partner",
        "partner-price-pct-lbl": "Add on",
        "partner-price-save-btn": "Save",
        "one-way": "One way",
        "hourly-way": "Hourly way",
        "calc-distance-lbl": "Est:",
        "time-location": "Local Time:",
        "tr-from": "From",
        "tr-to": "To",
        "tr-duration": "Duration",
        "tr-date": "Date",
        "tr-time": "Time",
        "svc-aea-edit-container-show-btn": "Back to service area",
        "distance-lbl-start": "Distance *",
        "distance-lbl": "Distance *",
        "distance-lbl-hourly-start": "Duration *",
        "distance-lbl-hourly": "Duration *",
        "start-price-box--lbl-": "Start Price *"
    }
}