var zhoTrans = {
    "after-sign-in": {
        "add-new-rule-text": "新增特定车型特定时间计价规则",
        "meet-greet-price-box--lbl-": "举牌费",
        "unit-price-box--lbl-": "每公里或英尺价 *",
        "unit-price-box-hourly--lbl-": "每小时价 *",
        "item-currency-0": "自营价格",
        "item-amounts-0": "供应商价格",
        "to-place": "输入送达地点",
        "from-place": "输入出发地点",
        "country": "输入机场名或机场三字码 *",
        "svc-aea-search-tab-title": "服务城市价格规则设置",
        "code-name": "新增服务机场 *",
        "service-area-search-fld": "输入服务城市或机场三字码搜索",
        "add-service-area-text": "新增服务城市",
        "svc-aea-btn": "服务",
        "vehicle-manage": "车辆管理",
        "partner-setting-btn": "合作伙伴",
        "servicing-airports-title": "服务区域",
        "basic-pricing-title": "按里程计价规则",
        "hourly-pricing-title": "钟点包车收费",
        "add-zones-title": "特定区域一口价",
        "vehicles-pricing-title": "按车型设置计价标准",
        "reserve-time-title": "急单加价规则",
        "personalised-time-title": "特定时间计价规则",
        "save-page-title": "保存",
        "prev-btn": "上一页",
        "next-btn": "下一页",
        "servicing-airports-save-btn": "保存",
        // "price-rule-setting-btn": "设置收费规则",
        "service-area-name-title": "服务城市",
        "service-airports-title": "服务机场",
        "service-radius-title": "设置服务范围半径",
        "btn-add-airport": "新增服务机场",
        "basic-price-text": "里程计价",
        "meet-sign-title": "举牌",
        "add-duration": "新增里程计价",
        "add-dis-pirce": "新增里程计价",
        "calc-btn": "测算",
        "calc-btn-hourly": "计算",
        "calculator-title": "按你设定的规则测算价格",
        "distance-import-fld": "输入行程距离测算",
        "calculator-title-hourly": "计算所设置的单价",
        "hourly-price-title": "钟点包车收费",
        "zone-pricing-explain": "设置一口价：为特定区域设置一口价",
        "zone-add-text": "新增特定区域一口价设置",
        "zone-reloc-fld": "新增特定区域一口价设置",
        "airport-names-lbl": "服务机场",
        "airport-prices-lbl": "一口价",
        "airport-distances-lbl": "里程",
        "small-vehicles-title": "小型车",
        "luxury-vehicles-title": "豪华轿车",
        "large-vehicles-title": "大型汽车",
        "currency-title": "币种：",
        "add-personalised-time": "新增时间段",
        "add-new-rule": "新增特定车型急单加价规则",
        "Normal-reserve-text": "正常预订",
        "in-advance": "提前预订",
        "extra-charge": "加价",
        "save-title": "确认保存",
        "btn-download": "下载价格规则表",
        "code-input": "验证码",
        "save-textarea": "请输入备注信息",
        "btn-save": "保存",
        "save-tip": "保存后您设置的价格规则将立即生效，请输入验证码确认保存",
        "partner-price-setting-title-bar": "合作伙伴",
        "add-partner": "添加合作伙伴",
        "partner-name-lbl": "名称",
        "partner-price-pct-lbl": "加价",
        "partner-price-save-btn": "保存",
        "one-way": "单次接送",
        "hourly-way": "按时包车",
        "calc-distance-lbl": "预估里程及时长",
        "time-location": "当地时间：",
        "tr-from": "起点",
        "tr-to": "终点",
        "tr-duration": "时长",
        "tr-date": "日期",
        "tr-time": "时间",
        "svc-aea-edit-container-show-btn": "返回当前的设置",
        "distance-lbl-start": "包含里程数 *",
        "distance-lbl": "里程 *",
        "distance-lbl-hourly-start": "包含时长 *",
        "distance-lbl-hourly": "超时收费 *",
        "start-price-box--lbl-": "起步价 *"
    }
}