export default [
  {
      "ID": 1,
      "XingCheng": "罐停止",
      "WenDu": 26.8,
      "YaLi": -0.00136714,
      "ZhuanSu": 0,
      "JiShi": 5840.72,
      "JinYeFa": 0,
      "ChuYeFa": 1,
      "JinQiFa": 0,
      "PaiQiFa": 0,
      "PaiXieFa": 0,
      "JiaCengJinShuiFa": 0,
      "JiaCengPaiShuiFa": 1,
      "JiaCengHuiQiFa": 0
  },
//   {
//       "ID": 2,
//       "XingCheng": "罐停止",
//       "WenDu": 27.5,
//       "YaLi": -0.000119351,
//       "ZhuanSu": 1,
//       "JiShi": 4413.32,
//       "JinYeFa": 1,
//       "ChuYeFa": 1,
//       "JinQiFa": 1,
//       "PaiQiFa": 1,
//       "PaiXieFa": 1,
//       "JiaCengJinShuiFa": 1,
//       "JiaCengPaiShuiFa": 1,
//       "JiaCengHuiQiFa": 1
//   },
//   {
//       "ID": 3,
//       "XingCheng": "罐停止",
//       "WenDu": 27.6,
//       "YaLi": -0.0000470132,
//       "ZhuanSu": 1,
//       "JiShi": 2675.55,
//       "JinYeFa": 1,
//       "ChuYeFa": 1,
//       "JinQiFa": 1,
//       "PaiQiFa": 1,
//       "PaiXieFa": 1,
//       "JiaCengJinShuiFa": 1,
//       "JiaCengPaiShuiFa": 1,
//       "JiaCengHuiQiFa": 1
//   },
//   {
//       "ID": 4,
//       "XingCheng": "罐停止",
//       "WenDu": 27.7,
//       "YaLi": -0.0000470132,
//       "ZhuanSu": 1,
//       "JiShi": 1298.93,
//       "JinYeFa": 1,
//       "ChuYeFa": 1,
//       "JinQiFa": 1,
//       "PaiQiFa": 1,
//       "PaiXieFa": 1,
//       "JiaCengJinShuiFa": 1,
//       "JiaCengPaiShuiFa": 1,
//       "JiaCengHuiQiFa": 1
//   }
]